import Link from "next/link";
import { SiteNav } from "@/components/site-nav";
import { ThemeToggle } from "@/components/theme-toggle";

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <SiteNav>
        <Link
          href="/"
          className="text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          Back to home
        </Link>
        <ThemeToggle />
      </SiteNav>

      <main className="flex-1 max-w-3xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-12">
        <div className="space-y-8">
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-foreground">Terms of Service</h1>
            <p className="mt-2 text-sm text-muted-foreground">Last updated: August 30, 2026</p>
          </div>

          <p className="text-sm text-foreground leading-relaxed">
            By using ArchAI, you agree to the following terms.
          </p>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">Description of Service</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              ArchAI is a tool that uses AI to generate example technical
              architecture blueprints (including suggested database schemas, API
              designs, folder structures, and roadmaps) based on a natural-language
              project description you provide.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">No Warranty on Generated Content</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Blueprints generated by ArchAI are produced by third-party AI models
              and are provided &quot;as is,&quot; for informational and inspirational
              purposes only. We make no guarantees about the accuracy, completeness,
              security, or production-readiness of any generated architecture, code
              structure, or recommendation. You are responsible for reviewing,
              validating, and adapting any generated content before relying on it,
              especially for security-sensitive decisions (authentication,
              authorization, payment handling, data storage).
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">Your Responsibilities</h2>
            <ul className="list-disc pl-5 space-y-1.5 text-sm text-muted-foreground">
              <li>
                You agree not to submit illegal, harmful, or abusive content as a
                project idea.
              </li>
              <li>
                You are responsible for any data you choose to submit; do not
                include real personal, confidential, or sensitive information in
                your project descriptions.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">No Account, No Guaranteed Availability</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Since ArchAI has no accounts or persistent server-side storage, we
              cannot recover lost history if your browser data is cleared. The
              service is provided without guarantee of uptime or availability, and
              may be modified, limited, or discontinued at any time.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">Third-Party AI Providers</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Generation requests are processed by third-party AI providers (OpenAI,
              Anthropic, or Groq). Your use of ArchAI is also subject to
              acceptable-use restrictions imposed by these providers.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">Intellectual Property</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              You retain ownership of the project ideas you submit. Generated
              blueprints are provided for your use; we do not claim ownership over
              the specific output generated for your prompts. ArchAI&apos;s own
              branding, design, and codebase (where open source, per the linked
              GitHub repository) are governed by their respective license terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">Limitation of Liability</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              ArchAI, its creator, and any contributors are not liable for any
              damages, losses, or issues arising from decisions made based on
              AI-generated architecture blueprints, including but not limited to
              security vulnerabilities, data loss, or financial harm.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">Changes to These Terms</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              These terms may be updated as the project evolves. Continued use after
              changes constitutes acceptance.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
